spring.application.name=api
# Server port config
server.port=8080

# Spring Data Cassandra Configurations
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=stock_keyspace
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=none